# Generated by Django 3.1.2 on 2021-03-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False)),
                ('C_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Pin_code', models.IntegerField()),
                ('Password', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=100)),
            ],
        ),
    ]
