# Generated by Django 3.1.2 on 2021-05-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addnewjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Companyac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('contact_no', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'companyac',
            },
        ),
        migrations.RenameField(
            model_name='company',
            old_name='CID',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Pin_code',
            new_name='pin_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='C_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='City',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='State',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='c_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='c_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_no',
            field=models.CharField(default='SOME STRING', max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='cp_name',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
