# Generated by Django 3.1.2 on 2021-05-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20210501_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='comp_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='c_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='cp_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
