# Generated by Django 3.1.2 on 2021-05-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Email',
            field=models.EmailField(max_length=30),
        ),
    ]
