# Generated by Django 3.1.2 on 2021-05-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0002_auto_20210501_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Review',
        ),
        migrations.AddField(
            model_name='faculty',
            name='clg_name',
            field=models.CharField(default=str, max_length=100),
        ),
    ]
